import Head from 'next/head'
import { Provider } from 'react-redux'
import cartReducer from '../Reducers/cartReducer'
import styles from '../styles/Home.module.css'
import Header from '../_layouts/Header/Header'
import ItemCard from '../_layouts/itemCard/itemCard'


export default function Home({itemData}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Shopping Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Provider store={cartReducer}>
      <Header/>
      <main className={styles.main}>
        {itemData.map(item => <ItemCard key={item.id} data={item}></ItemCard>)}
      </main>
      </Provider>
    </div>
  )
}

export async function getServerSideProps() {
  let response = await fetch('http://localhost:3000/api/items')
  let itemData = await response.json()

  // let cart = await fetch('http://localhost:3000/api/cart')
  // let cartData = await cart.json()

  return {
    props: {itemData}
  }
} 
