import { useState } from "react";
import Head from "next/head";
import Header from "../_layouts/Header/Header";
import cartReducer from "../Reducers/cartReducer";
import styles from '../styles/Home.module.css'
import { Provider, useDispatch } from "react-redux";

import AuthService from "../services/auth.service";
import { useRouter } from "next/router";




function loginPage() {
const [pageStatus, setPageStatus] = useState("login")
const [email, setEmail] = useState("")
const [password, setPassword] = useState("")
// const dispatch = useDispatch()

const router = useRouter();

const onChangeEmail = (e) => {
    const email = e.target.value;
    setEmail(email);
  };

  const onChangePassword = (e) => {
    const password = e.target.value;
    setPassword(password);
  };

  const handleLogin = (e) => {
    e.preventDefault();

    AuthService.login(email, password).then(
    () => {
        // dispatch({type: "ADD_DATA", data: AuthService.getCurrentUser()})
        router.push("/profile")
    },
    (error) => {
        const resMessage =
        (error.response &&
            error.response.data &&
            error.response.data.message) ||
        error.message ||
        error.toString();
    }
    );
  };


    return ( 
        <div>
        <Head>
            <title>Login</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

            <Provider store={cartReducer}>
            <Header/>
            </Provider>
            <div className={styles.authPage}>
                <form className={styles.Form} onSubmit={handleLogin}>
                    <h1>Авторизация</h1>
                    <div className={styles.formInput}>
                        <label htmlFor="email">Email:</label>
                        <input onChange={onChangeEmail} type="email" name="email" id="email" placeholder="IvanIvanov@mail.ru"  />                        
                    </div>
                    <div className={styles.formInput}>
                        <label htmlFor="password">Пароль:</label>
                        <input onChange={onChangePassword} type="password" name="password" id="password" placeholder="password" />                        
                    </div>
                    <button type="submit" className={styles.submitButton}>Войти</button>
                    <button onClick={()=>setPageStatus("register")} className={styles.registerButton}>Зарегистрироваться</button>
                </form>
            </div>
        </div> 
    );
}

export default loginPage;

// export async function getServerSideProps() {
//     let response = await fetch(`http://localhost:3000/api/profile`)
//     let userData = await response.json()
//     return {
//       props: {userData}
//     }
//   } 