import { useState } from "react";
import Head from "next/head";
import Header from "../_layouts/Header/Header";
import cartReducer from "../Reducers/cartReducer";
import styles from '../styles/Home.module.css'
import { Provider, useSelector } from "react-redux";
import { UserOutlined } from "@ant-design/icons";
import { useEffect } from "react";
import AuthService from "../services/auth.service";
import { Spin } from "antd";
import { useRouter } from "next/router";

function userPage({userData}) {
    const [user, setUser] = useState(null)
    const router = useRouter();

    useEffect(() => {
        let user = AuthService.getCurrentUser()
        if (!user) router.push("/login")
        setUser(user)
    }, []);

    userData = userData[0]
    return ( 
        <div>
        <Head>
            <title>Profile</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

            <Provider store={cartReducer}>
            <Header/>
            { user ? 
            <div className={styles.info}>
                <div className={styles.avatar}><UserOutlined/></div>
                <p className={styles.name}>{user.name} {userData.secondName} {user.surname}</p>
                <div className={styles.otherInfo}>
                    <p>Телефон: {userData.phone}</p>
                    <p>e-mail: {user.email}</p>                    
                </div>
                <div className={styles.orders}>
                    <p>Заказы:</p>
                    <div className={styles.orderItems}>
                        <div className={styles.orderItem}>
                            <img className={styles.itemImg} src="https://photo_cache.hb.bizmrg.com/Render/rnd000000317/341c8529-cfa3-4a99-9698-314da4333706.png"></img>
                            <div className={styles.itemList}>
                                <h3>Haval Jolion</h3>
                                <p>Номер заказа: 57712391901</p>
                                <p>Дата заказа: 24.01.2022</p>
                                <p>Количество: 1 шт.</p>
                                <p>Стоимость: <u><b>3.123.555</b></u> р</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            :
            <Spin size="large"/>}
            </Provider>
        </div> 
    );
}

export default userPage;

export async function getServerSideProps() {

    let response = await fetch(`http://localhost:3000/api/profile`)
    let userData = await response.json()
    return {
      props: {userData}
    }
  } 