import { useState } from "react";
import Head from "next/head";
import Header from "../_layouts/Header/Header";
import cartReducer from "../Reducers/cartReducer";
import styles from '../styles/Home.module.css'
import { Provider, useSelector } from "react-redux";
import { UserOutlined } from "@ant-design/icons";
import { useEffect } from "react";
import AuthService from "../services/auth.service";
import { Spin } from "antd";
import { useRouter } from "next/router";
import OrderItem from "../_layouts/UI/order";

function userPage({itemData}) {
    const [user, setUser] = useState(null)
    const [orders, setOrders] = useState(null)
    const router = useRouter();
    

    useEffect(() => {
        let user = AuthService.getCurrentUser()
        console.log(user)
        if (!user) {
            router.push("/login")
            return
        }

        AuthService.getOrders().then((order) => setOrders(order))
        setUser(user)
    }, []);

    // console.log(orders)
    let cars
    if (orders) {
            cars = orders.map((order) => order.vehicle = itemData[order.vehicle_id - 1])
    }
    let type = "user"
    console.log(cars)
    return ( 
        <div>
        <Head>
            <title>Profile</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

            <Provider store={cartReducer}>
            <Header/>
            { user ? 
            <div className={styles.info}>
                <div className={styles.avatar}><UserOutlined/></div>
                <p className={styles.name}>{user.name} {user.surname}</p>
                <div className={styles.otherInfo}>
                    <p>Телефон: {user.phone}</p>
                    <p>e-mail: {user.email}</p>                    
                </div>
                { user.roles.includes("ROLE_MANAGER") ? 
                    <button className={styles.adminButton} onClick={(e) => router.push("/admin")}>Админ-панель</button>
                    : ""
                }
                <div className={styles.orders}>
                    <p>Заказы:</p>
                    <div className={styles.orderItems}>
                        {orders ? orders.map(order => <OrderItem key={order.id} data={{order, type}}></OrderItem>) : <Spin size="large"/>}
                    </div>
                </div>
            </div>
            :
            <Spin size="large"/>}
            </Provider>
        </div> 
    );
}

export default userPage;

export async function getServerSideProps() {
    let response = await fetch('http://localhost:3000/api/items')
    let itemData = await response.json()
  
    // let cart = await fetch('http://localhost:3000/api/cart')
    // let cartData = await cart.json()
  
    return {
      props: {itemData}
    }
  } 