import { useState } from "react";
import Head from "next/head";
import Header from "../_layouts/Header/Header";
import cartReducer from "../Reducers/cartReducer";
import styles from '../styles/Home.module.css'
import { Provider } from "react-redux";
import { UserOutlined } from "@ant-design/icons";

function userPage({userData}) {
    userData = userData[0]
    return ( 
        <div>
        <Head>
            <title>Profile</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

            <Provider store={cartReducer}>
            <Header/>
            </Provider>
            <div className={styles.info}>
                <div className={styles.avatar}><UserOutlined/></div>
                <p className={styles.name}>{userData.name} {userData.secondName} {userData.surname}</p>
                <div className={styles.otherInfo}>
                    <p>Телефон: {userData.phone}</p>
                    <p>e-mail: {userData.email}</p>                    
                </div>
            </div>
        </div> 
    );
}

export default userPage;

export async function getServerSideProps() {
    let response = await fetch(`http://localhost:3000/api/profile`)
    let userData = await response.json()
    return {
      props: {userData}
    }
  } 