import { useState } from "react";
import Head from "next/head";
import Header from "../_layouts/Header/Header";
import cartReducer from "../Reducers/cartReducer";
import styles from '../styles/Home.module.css'
import { Provider, useDispatch } from "react-redux";

import AuthService from "../services/auth.service";
import { useRouter } from "next/router";




function registerPage() {
const [pageStatus, setPageStatus] = useState("login")
const [email, setEmail] = useState("")
const [password, setPassword] = useState("")
const [name, setName] = useState("")
const [surname, setSurname] = useState("")
// const dispatch = useDispatch()

const router = useRouter();

const onChangeEmail = (e) => {
    const email = e.target.value;
    setEmail(email);
};

const onChangePassword = (e) => {
    const password = e.target.value;
    setPassword(password);
};

const onChangeName = (e) => {
    const name = e.target.value;
    setName(name);
};

const onChangeSurname = (e) => {
    const surname = e.target.value;
    setSurname(surname);
};

const handleLogin = (e) => {
    e.preventDefault();

    AuthService.register(name, surname, email, password).then(
    () => {
        // dispatch({type: "ADD_DATA", data: AuthService.getCurrentUser()})
        router.push("/login")
    },
    (error) => {
        const resMessage =
        (error.response &&
            error.response.data &&
            error.response.data.message) ||
        error.message ||
        error.toString();
    }
    );
  };


    return ( 
        <div>
        <Head>
            <title>Register</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

            <Provider store={cartReducer}>
            <Header/>
            </Provider>
            <div className={styles.authPage} style={{height: "350px"}}>
                <form className={styles.Form} onSubmit={handleLogin}>
                    <h1>Регистрация</h1>
                    <div className={styles.formInput}>
                        <label htmlFor="name">Имя:</label>
                        <input onChange={onChangeName} type="text" name="name" id="name" placeholder="Иван"  />                        
                    </div>
                    <div className={styles.formInput}>
                        <label htmlFor="surname">Фамилия:</label>
                        <input onChange={onChangeSurname} type="text" name="surname" id="surname" placeholder="Иванов"  />                        
                    </div>
                    <div className={styles.formInput}>
                        <label htmlFor="email">Email:</label>
                        <input onChange={onChangeEmail} type="email" name="email" id="email" placeholder="IvanIvanov@mail.ru"  />                        
                    </div>
                    <div className={styles.formInput}>
                        <label htmlFor="password">Пароль:</label>
                        <input onChange={onChangePassword} type="password" name="password" id="password" placeholder="password" />                        
                    </div>
                    <button type="submit" style={{width: "250px"}} className={styles.submitButton}>Зарегистрироваться</button>
                </form>
            </div>
        </div> 
    );
}

export default registerPage;

// export async function getServerSideProps() {
//     let response = await fetch(`http://localhost:3000/api/profile`)
//     let userData = await response.json()
//     return {
//       props: {userData}
//     }
//   } 